export class ExportService {
  static generateMarkdown(code: string, review: string, language: string): string {
    return `# Code Review Report

**Language**: ${language}
**Date**: ${new Date().toLocaleString()}

---

## Original Code

\`\`\`${language}
${code}
\`\`\`

---

## Review

${review}

---

*Generated by AI Code Review Bot powered by Cloudflare Workers AI*
`;
  }
}